import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" data-theme="winter">
      <body className={inter.className}>
        <div className='bg-slate-800 text-white w-full text-3xl py-3 px-2 shadow'>
          <Link href="/">Next.js</Link>
        </div>
        <div className='px-2'>
          {children}
        </div>
      </body>
    </html>
  )
}
